kind: Application

server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: bravi
  jpa:
    hibernate:
      ddl-auto: validate                              # перевірка відповідності entity і таблиць
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloack.base-url}/realms/${keycloack.realm}

logging:
  pattern:
    level: "%5p [%X{requestId:-}]"
  level:
    root: INFO
    ua.com.bravi.bravi: ${APP_LOG_LEVEL:DEBUG}
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
      springframework:
        security: DEBUG
        web: DEBUG

keycloack:
  base-url: http://localhost:8080
  realm: bravi
  client-id: backend-service

bravi:
  security:
    internal-role: ${INTERNAL_API_ROLE:auth_service}
    user-role: ${USER_API_ROLE:bravi_user}

catalog:
  products:
    image-storage:
      base-path: ${PRODUCT_IMAGE_PATH:./data/product-images}
      max-file-size: 5MB

