CREATE TABLE products
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id          BIGINT        NOT NULL,
    category_id       BIGINT,
    manufacturer_id   BIGINT,
    stock_status_id   BIGINT        NOT NULL,
    name              VARCHAR(255)  NOT NULL,
    sku               VARCHAR(128),
    code              VARCHAR(128)  NOT NULL,
    description       TEXT,
    partner_price     NUMERIC(19, 4) NOT NULL,
    recommended_price NUMERIC(19, 4) NOT NULL,
    quantity          INTEGER       NOT NULL DEFAULT 0,
    weight            NUMERIC(12, 3),
    width             NUMERIC(12, 3),
    height            NUMERIC(12, 3),
    length            NUMERIC(12, 3),
    status            VARCHAR(32)   NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products ADD CONSTRAINT fk_products_on_store
    FOREIGN KEY (store_id) REFERENCES stores (id);
ALTER TABLE products ADD CONSTRAINT fk_products_on_category
    FOREIGN KEY (category_id) REFERENCES categories (id);
ALTER TABLE products ADD CONSTRAINT fk_products_on_manufacturer
    FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (id);
ALTER TABLE products ADD CONSTRAINT fk_products_on_stock_status
    FOREIGN KEY (stock_status_id) REFERENCES stock_statuses (id);

ALTER TABLE products ADD CONSTRAINT uq_products_store_code UNIQUE (store_id, code);
CREATE UNIQUE INDEX uq_products_store_sku ON products (store_id, sku) WHERE sku IS NOT NULL;

CREATE INDEX idx_products_store_id ON products (store_id);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_manufacturer_id ON products (manufacturer_id);
CREATE INDEX idx_products_stock_status_id ON products (stock_status_id);
CREATE INDEX idx_products_created_at ON products (created_at);
CREATE INDEX idx_products_name_lower ON products (lower(name));
