-- Seller onboarding: one default store per seller account + a sales channel per store.

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_seller_account UNIQUE (seller_account_id);

CREATE TABLE sales_channels
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id  VARCHAR(255)                            NOT NULL,
    store_id   BIGINT                                  NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    settings   JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sales_channels PRIMARY KEY (id)
);

ALTER TABLE sales_channels
    ADD CONSTRAINT uc_sales_channels_public_id UNIQUE (public_id);
ALTER TABLE sales_channels
    ADD CONSTRAINT uc_sales_channels_store_type UNIQUE (store_id, type);
ALTER TABLE sales_channels
    ADD CONSTRAINT fk_sales_channels_on_store FOREIGN KEY (store_id) REFERENCES stores (id);
