CREATE TABLE product_images
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id        BIGINT       NOT NULL,
    storage_key       VARCHAR(512) NOT NULL,
    content_type      VARCHAR(128),
    size_bytes        BIGINT,
    original_filename VARCHAR(255),
    sort_order        INTEGER      NOT NULL DEFAULT 0,
    is_primary        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

ALTER TABLE product_images ADD CONSTRAINT fk_product_images_on_product
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE;

CREATE INDEX idx_product_images_product_id ON product_images (product_id);
