-- System-wide reference data: dictionary types + their items.

CREATE TABLE dictionaries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(64)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dictionaries PRIMARY KEY (id),
    CONSTRAINT uq_dictionaries_code UNIQUE (code)
);

CREATE TABLE dictionary_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dictionary_id BIGINT       NOT NULL,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(255) NOT NULL,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    meta          JSONB        NOT NULL DEFAULT '{}',
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dictionary_items PRIMARY KEY (id),
    CONSTRAINT uq_dictionary_items_dictionary_code UNIQUE (dictionary_id, code)
);

ALTER TABLE dictionary_items ADD CONSTRAINT fk_dictionary_items_on_dictionary
    FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id);
