CREATE TABLE order_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(64)  NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_order_statuses PRIMARY KEY (id),
    CONSTRAINT uq_order_statuses_code UNIQUE (code)
);

INSERT INTO order_statuses (code, name)
VALUES ('NEW', 'Нове'),
       ('PROCESSING', 'В обробці'),
       ('SHIPPED', 'Відправлено'),
       ('DELIVERED', 'Доставлено'),
       ('CANCELLED', 'Скасовано');
