CREATE TABLE orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id              BIGINT        NOT NULL,
    buyer_id              BIGINT        NOT NULL,
    status_id             BIGINT        NOT NULL,
    recipient_first_name  VARCHAR(255)  NOT NULL,
    recipient_last_name   VARCHAR(255)  NOT NULL,
    recipient_phone       VARCHAR(32),
    recipient_email       VARCHAR(255),
    delivery_method_code  VARCHAR(64)   NOT NULL,
    delivery_type         VARCHAR(32)   NOT NULL,
    delivery_country      VARCHAR(128),
    delivery_region       VARCHAR(128),
    delivery_city         VARCHAR(128),
    delivery_address      VARCHAR(512),
    delivery_extra        VARCHAR(512),
    delivery_warehouse_no VARCHAR(64),
    payment_method_code   VARCHAR(64)   NOT NULL,
    prepayment            NUMERIC(19, 4),
    currency              VARCHAR(3)    NOT NULL,
    subtotal              NUMERIC(19, 4) NOT NULL,
    discount_total        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    shipping_total        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total                 NUMERIC(19, 4) NOT NULL,
    comment               TEXT,
    internal_comment      TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders ADD CONSTRAINT fk_orders_on_store
    FOREIGN KEY (store_id) REFERENCES stores (id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_on_status
    FOREIGN KEY (status_id) REFERENCES order_statuses (id);

CREATE INDEX idx_orders_store_id   ON orders (store_id);
CREATE INDEX idx_orders_buyer_id   ON orders (buyer_id);
CREATE INDEX idx_orders_status_id  ON orders (status_id);
CREATE INDEX idx_orders_created_at ON orders (created_at);
CREATE INDEX idx_orders_recipient_last_name_lower ON orders (lower(recipient_last_name));
