CREATE TABLE order_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id      BIGINT        NOT NULL,
    product_id    BIGINT        NOT NULL,
    sku           VARCHAR(128),
    code          VARCHAR(128)  NOT NULL,
    name          VARCHAR(255)  NOT NULL,
    quantity      INTEGER       NOT NULL,
    partner_price NUMERIC(19, 4) NOT NULL,
    sale_price    NUMERIC(19, 4) NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_on_order
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
