CREATE TABLE order_shipments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id        BIGINT      NOT NULL,
    carrier_code    VARCHAR(64),
    tracking_number VARCHAR(128),
    delivery_status VARCHAR(64),
    raw_payload     JSONB       NOT NULL DEFAULT '{}',
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_shipments PRIMARY KEY (id),
    CONSTRAINT uq_order_shipments_order UNIQUE (order_id)
);

ALTER TABLE order_shipments ADD CONSTRAINT fk_order_shipments_on_order
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
