CREATE TABLE accounts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id  VARCHAR(255)                            NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_public_id UNIQUE (public_id);
