CREATE TABLE memberships
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id          VARCHAR(255)                            NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    account_id         BIGINT                                  NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    invited_by_user_id BIGINT,
    invited_at         TIMESTAMP WITHOUT TIME ZONE,
    joined_at          TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_memberships PRIMARY KEY (id)
);

ALTER TABLE memberships
    ADD CONSTRAINT uc_memberships_public_id UNIQUE (public_id);

ALTER TABLE memberships
    ADD CONSTRAINT uc_memberships_user_account UNIQUE (user_id, account_id);

ALTER TABLE memberships
    ADD CONSTRAINT fk_memberships_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE memberships
    ADD CONSTRAINT fk_memberships_on_account FOREIGN KEY (account_id) REFERENCES accounts (id);

ALTER TABLE memberships
    ADD CONSTRAINT fk_memberships_on_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users (id);

CREATE INDEX idx_memberships_user_id ON memberships (user_id);
CREATE INDEX idx_memberships_account_id ON memberships (account_id);
