-- RBAC core: roles, permissions and their join tables.

CREATE TABLE roles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id    VARCHAR(255)                            NOT NULL,
    account_id   BIGINT, -- NULL => system role (platform-wide template); NOT NULL => account-custom role
    code         VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(512),
    account_type VARCHAR(255)                            NOT NULL,
    is_system    BOOLEAN                                 NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_public_id UNIQUE (public_id);

ALTER TABLE roles
    ADD CONSTRAINT fk_roles_on_account FOREIGN KEY (account_id) REFERENCES accounts (id);

-- code unique among system roles, and unique per account for custom roles
CREATE UNIQUE INDEX uc_roles_system_code ON roles (code) WHERE account_id IS NULL;
CREATE UNIQUE INDEX uc_roles_account_code ON roles (account_id, code) WHERE account_id IS NOT NULL;


CREATE TABLE permissions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code         VARCHAR(255)                            NOT NULL,
    resource     VARCHAR(255)                            NOT NULL,
    action       VARCHAR(255)                            NOT NULL,
    account_type VARCHAR(255),
    description  VARCHAR(512),
    status       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_code UNIQUE (code);


CREATE TABLE membership_roles
(
    membership_id       BIGINT                      NOT NULL,
    role_id             BIGINT                      NOT NULL,
    assigned_by_user_id BIGINT,
    assigned_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_membership_roles PRIMARY KEY (membership_id, role_id)
);

ALTER TABLE membership_roles
    ADD CONSTRAINT fk_membership_roles_on_membership FOREIGN KEY (membership_id) REFERENCES memberships (id);

ALTER TABLE membership_roles
    ADD CONSTRAINT fk_membership_roles_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE membership_roles
    ADD CONSTRAINT fk_membership_roles_on_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users (id);


CREATE TABLE role_permissions
(
    role_id       BIGINT                      NOT NULL,
    permission_id BIGINT                      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);
