-- Product attributes: a global template library, store-owned definitions with option lists,
-- category bindings inherited down the category tree, and typed product values.

CREATE TABLE attribute_templates
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    value_type           VARCHAR(32)  NOT NULL,
    unit_dictionary_code VARCHAR(64),
    unit_default_code    VARCHAR(64),
    variant_defining     BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order           INTEGER      NOT NULL DEFAULT 0,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_attribute_templates PRIMARY KEY (id),
    CONSTRAINT uq_attribute_templates_code UNIQUE (code)
);


CREATE TABLE attribute_template_options
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id BIGINT       NOT NULL,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_attribute_template_options PRIMARY KEY (id),
    CONSTRAINT uq_attribute_template_options_template_code UNIQUE (template_id, code)
);

ALTER TABLE attribute_template_options ADD CONSTRAINT fk_attribute_template_options_on_template
    FOREIGN KEY (template_id) REFERENCES attribute_templates (id) ON DELETE CASCADE;
CREATE INDEX idx_attribute_template_options_template_id ON attribute_template_options (template_id);


CREATE TABLE store_attributes
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id            VARCHAR(255) NOT NULL,
    store_id             BIGINT       NOT NULL,
    template_code        VARCHAR(64),
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    description          TEXT,
    value_type           VARCHAR(32)  NOT NULL,
    scope                VARCHAR(32)  NOT NULL DEFAULT 'CATEGORY',
    unit_dictionary_code VARCHAR(64),
    unit_default_code    VARCHAR(64),
    variant_defining     BOOLEAN      NOT NULL DEFAULT FALSE,
    status               VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_attributes PRIMARY KEY (id),
    CONSTRAINT uc_store_attributes_public_id UNIQUE (public_id),
    CONSTRAINT uq_store_attributes_store_code UNIQUE (store_id, code)
);

ALTER TABLE store_attributes ADD CONSTRAINT fk_store_attributes_on_store
    FOREIGN KEY (store_id) REFERENCES stores (id);
CREATE INDEX idx_store_attributes_store_id ON store_attributes (store_id);
CREATE INDEX idx_store_attributes_store_scope ON store_attributes (store_id, scope);


CREATE TABLE store_attribute_options
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id    VARCHAR(255) NOT NULL,
    attribute_id BIGINT       NOT NULL,
    code         VARCHAR(64)  NOT NULL,
    name         VARCHAR(255) NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_store_attribute_options PRIMARY KEY (id),
    CONSTRAINT uc_store_attribute_options_public_id UNIQUE (public_id),
    CONSTRAINT uq_store_attribute_options_attribute_code UNIQUE (attribute_id, code)
);

ALTER TABLE store_attribute_options ADD CONSTRAINT fk_store_attribute_options_on_attribute
    FOREIGN KEY (attribute_id) REFERENCES store_attributes (id) ON DELETE CASCADE;
CREATE INDEX idx_store_attribute_options_attribute_id ON store_attribute_options (attribute_id);

-- Deferred so a reorder may pass through transient duplicates inside one transaction.
ALTER TABLE store_attribute_options ADD CONSTRAINT uq_store_attribute_options_attribute_sort
    UNIQUE (attribute_id, sort_order) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE store_attribute_options ADD CONSTRAINT ck_store_attribute_options_sort_order
    CHECK (sort_order >= 0);


CREATE TABLE store_category_attributes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id  BIGINT  NOT NULL,
    attribute_id BIGINT  NOT NULL,
    sort_order   INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_store_category_attributes PRIMARY KEY (id),
    CONSTRAINT uq_store_category_attributes_pair UNIQUE (category_id, attribute_id)
);

ALTER TABLE store_category_attributes ADD CONSTRAINT fk_store_category_attributes_on_category
    FOREIGN KEY (category_id) REFERENCES store_categories (id) ON DELETE CASCADE;
ALTER TABLE store_category_attributes ADD CONSTRAINT fk_store_category_attributes_on_attribute
    FOREIGN KEY (attribute_id) REFERENCES store_attributes (id) ON DELETE CASCADE;
CREATE INDEX idx_store_category_attributes_category_id ON store_category_attributes (category_id);
CREATE INDEX idx_store_category_attributes_attribute_id ON store_category_attributes (attribute_id);

ALTER TABLE store_category_attributes ADD CONSTRAINT uq_store_category_attributes_category_sort
    UNIQUE (category_id, sort_order) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE store_category_attributes ADD CONSTRAINT ck_store_category_attributes_sort_order
    CHECK (sort_order >= 0);


CREATE TABLE store_product_attribute_values
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    BIGINT  NOT NULL,
    attribute_id  BIGINT  NOT NULL,
    option_id     BIGINT,
    value_string  TEXT,
    value_number  NUMERIC(19, 6),
    value_boolean BOOLEAN,
    value_date    DATE,
    unit_code     VARCHAR(64),
    sort_order    INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_product_attribute_values PRIMARY KEY (id)
);

ALTER TABLE store_product_attribute_values ADD CONSTRAINT fk_store_product_attribute_values_on_product
    FOREIGN KEY (product_id) REFERENCES store_products (id) ON DELETE CASCADE;
-- No cascade: a definition still carrying product values must not vanish silently.
ALTER TABLE store_product_attribute_values ADD CONSTRAINT fk_store_product_attribute_values_on_attribute
    FOREIGN KEY (attribute_id) REFERENCES store_attributes (id);
ALTER TABLE store_product_attribute_values ADD CONSTRAINT fk_store_product_attribute_values_on_option
    FOREIGN KEY (option_id) REFERENCES store_attribute_options (id);

-- One row per scalar value; a multi-select keeps one row per chosen option.
CREATE UNIQUE INDEX uq_store_product_attribute_values_slot
    ON store_product_attribute_values (product_id, attribute_id, COALESCE(option_id, 0));
CREATE INDEX idx_store_product_attribute_values_product_id
    ON store_product_attribute_values (product_id);
CREATE INDEX idx_store_product_attribute_values_attribute_id
    ON store_product_attribute_values (attribute_id);
-- Backs the previously-used-value suggestions for free-text attributes.
CREATE INDEX idx_store_product_attribute_values_text
    ON store_product_attribute_values (attribute_id, lower(value_string));

ALTER TABLE store_product_attribute_values ADD CONSTRAINT ck_store_product_attribute_values_sort_order
    CHECK (sort_order >= 0);
