-- A product's discount schedule: standalone dated records owned by one product. At most one may be
-- in effect at any instant, so the periods of one product never overlap. The period is half-open
-- [starts_at, ends_at); a NULL ends_at is an open upper bound and therefore occupies the whole axis
-- after its start, which is what stops it from preceding a later discount.
-- Every instant column is UTC (hibernate.jdbc.time_zone: UTC), as everywhere else in this schema.

-- Lets one exclusion constraint combine equality on product_id with range overlap. Trusted
-- extension since PostgreSQL 13, so the database owner may create it without superuser rights.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE store_product_discounts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id  VARCHAR(255)                NOT NULL,
    product_id BIGINT                      NOT NULL,
    type       VARCHAR(32)                 NOT NULL,
    value      NUMERIC(19, 4)              NOT NULL,
    starts_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ends_at    TIMESTAMP WITHOUT TIME ZONE,
    label      VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_product_discounts PRIMARY KEY (id),
    CONSTRAINT uc_store_product_discounts_public_id UNIQUE (public_id)
);

-- Owned child: a deleted product takes its discounts with it, like store_product_images.
ALTER TABLE store_product_discounts
    ADD CONSTRAINT fk_store_product_discounts_on_product
        FOREIGN KEY (product_id) REFERENCES store_products (id) ON DELETE CASCADE;

ALTER TABLE store_product_discounts
    ADD CONSTRAINT ck_store_product_discounts_period
        CHECK (ends_at IS NULL OR ends_at > starts_at);

-- The percent range is a fixed business rule and belongs in the schema; "amount below the product
-- price" spans two tables and stays a check of the application.
ALTER TABLE store_product_discounts
    ADD CONSTRAINT ck_store_product_discounts_value
        CHECK ((type = 'PERCENT' AND value >= 0.01 AND value <= 99)
            OR (type = 'AMOUNT' AND value > 0));

-- The invariant itself: one product, never two overlapping periods. A NULL ends_at makes the range
-- unbounded above, so an open-ended discount collides with every later one and the open-ended rule
-- needs no special case. tsrange rather than tstzrange because the columns are timestamp without
-- time zone: the implicit cast to timestamptz is STABLE, not IMMUTABLE, and PostgreSQL rejects it
-- inside a constraint expression.
ALTER TABLE store_product_discounts
    ADD CONSTRAINT ex_store_product_discounts_no_overlap
        EXCLUDE USING gist (product_id WITH =, tsrange(starts_at, ends_at, '[)') WITH &&);

-- Backs "which discount is in effect for products X.. at instant T": the single read, the page
-- batch and the EXISTS subquery of the has_active_discount filter all emit this shape.
CREATE INDEX idx_store_product_discounts_product_period
    ON store_product_discounts (product_id, starts_at, ends_at);
