-- Tags: a store-scoped dictionary of labels the seller pins on things, plus the many-to-many link
-- between a tag and what it labels. A tag is internal to the seller — like a discount's label, it
-- is never shown to a buyer — so it carries nothing but a name and a status: no slug, no colour,
-- no description, no ordering.
--
-- Tags are created implicitly: saving a product with a tag name the store does not own yet mints
-- the tag. That makes the normalized name, not the public id, the real key of the dictionary.
--
-- One dictionary serves every kind of taggable thing, told apart by target. Products and orders
-- keep separate vocabularies, so target is part of the name's uniqueness. The link, in contrast,
-- gets one table per target: a single polymorphic link table could not carry a foreign key, and
-- the cascade from the tagged row is what keeps links from outliving it.

CREATE TABLE store_tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id  VARCHAR(255)                NOT NULL,
    store_id   BIGINT                      NOT NULL,
    target     VARCHAR(32)                 NOT NULL,
    name       VARCHAR(64)                 NOT NULL,
    status     VARCHAR(32)                 NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_tags PRIMARY KEY (id),
    CONSTRAINT uc_store_tags_public_id UNIQUE (public_id)
);

ALTER TABLE store_tags
    ADD CONSTRAINT fk_store_tags_on_store FOREIGN KEY (store_id) REFERENCES stores (id);
CREATE INDEX idx_store_tags_store_target ON store_tags (store_id, target);

-- The natural key. "Хіт" and "хіт" are one tag, so the dictionary is deduplicated by the database
-- rather than by a read-then-write check that two concurrent saves would both pass.
-- An expression index rather than a UNIQUE constraint, because a constraint cannot span lower(name);
-- the application infers this index in ON CONFLICT and reads its name back out of a violation.
CREATE UNIQUE INDEX uq_store_tags_store_target_name_lower
    ON store_tags (store_id, target, lower(name));


CREATE TABLE store_product_tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                      NOT NULL,
    tag_id     BIGINT                      NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_store_product_tags PRIMARY KEY (id),
    CONSTRAINT uq_store_product_tags_pair UNIQUE (product_id, tag_id)
);

-- Cascading both ways: the row is a link and carries no data of its own. Deleting a tag therefore
-- untags its products instead of being refused the way an attribute with values is — a label the
-- seller stopped using is meant to disappear, and nothing is lost with it.
ALTER TABLE store_product_tags
    ADD CONSTRAINT fk_store_product_tags_on_product
        FOREIGN KEY (product_id) REFERENCES store_products (id) ON DELETE CASCADE;
ALTER TABLE store_product_tags
    ADD CONSTRAINT fk_store_product_tags_on_tag
        FOREIGN KEY (tag_id) REFERENCES store_tags (id) ON DELETE CASCADE;

-- Backs the tag_ids product filter, whose subquery probes by tag first. The reverse direction
-- ("which tags does this product carry") rides the leading column of uq_store_product_tags_pair,
-- so it needs no index of its own.
CREATE INDEX idx_store_product_tags_tag_id ON store_product_tags (tag_id);
