CREATE TABLE stores
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seller_id          BIGINT                                  NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        TEXT,
    country            VARCHAR(255),
    region             VARCHAR(255),
    city               VARCHAR(255),
    postal_code        VARCHAR(25),
    address            VARCHAR(255),
    address_additional VARCHAR(255),
    timezone           VARCHAR(64)                             NOT NULL,
    logo_url           VARCHAR(512),
    working_hours      JSONB,
    currency           VARCHAR(3)                              NOT NULL,
    allow_return       BOOLEAN                                 NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_seller UNIQUE (seller_id);

ALTER TABLE stores
    ADD CONSTRAINT FK_STORES_ON_SELLER FOREIGN KEY (seller_id) REFERENCES users (id);