CREATE TABLE store_contacts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id   BIGINT                                  NOT NULL,
    type       VARCHAR(32)                             NOT NULL,
    value      VARCHAR(512)                            NOT NULL,
    comment    VARCHAR(512),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_contacts PRIMARY KEY (id)
);

ALTER TABLE store_contacts
    ADD CONSTRAINT FK_STORE_CONTACTS_ON_STORE FOREIGN KEY (store_id) REFERENCES stores (id);

CREATE INDEX idx_store_contacts_store_id ON store_contacts (store_id);
