CREATE TABLE store_payment_methods
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id    BIGINT                                  NOT NULL,
    method_code VARCHAR(64)                             NOT NULL,
    enabled     BOOLEAN                                 NOT NULL DEFAULT FALSE,
    config      JSONB                                   NOT NULL DEFAULT '{}',
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_payment_methods PRIMARY KEY (id),
    CONSTRAINT uq_store_payment_methods_store_method UNIQUE (store_id, method_code)
);

ALTER TABLE store_payment_methods
    ADD CONSTRAINT FK_STORE_PAYMENT_METHODS_ON_STORE FOREIGN KEY (store_id) REFERENCES stores (id);

CREATE INDEX idx_store_payment_methods_store_id ON store_payment_methods (store_id);
