-- Stores now belong to a SELLER_ACCOUNT (1..N), not directly to a user.
CREATE TABLE stores
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id          VARCHAR(255)                            NOT NULL,
    seller_account_id  BIGINT                                  NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        TEXT,
    country            VARCHAR(255),
    region             VARCHAR(255),
    city               VARCHAR(255),
    postal_code        VARCHAR(25),
    address            VARCHAR(255),
    address_additional VARCHAR(255),
    timezone           VARCHAR(64)                             NOT NULL,
    logo_url           VARCHAR(512),
    working_hours      JSONB,
    currency           VARCHAR(3)                              NOT NULL,
    allow_return       BOOLEAN                                 NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_public_id UNIQUE (public_id);
ALTER TABLE stores
    ADD CONSTRAINT fk_stores_on_seller_account FOREIGN KEY (seller_account_id) REFERENCES seller_accounts (account_id);

CREATE INDEX idx_stores_seller_account_id ON stores (seller_account_id);


-- Per-store default settings (ERD STORE_SETTINGS).
CREATE TABLE store_settings
(
    store_id               BIGINT                      NOT NULL,
    default_weight_unit    VARCHAR(16),
    default_dimension_unit VARCHAR(16),
    default_currency       VARCHAR(3),
    default_language       VARCHAR(8),
    timezone               VARCHAR(64),
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_settings PRIMARY KEY (store_id)
);

ALTER TABLE store_settings
    ADD CONSTRAINT fk_store_settings_on_store FOREIGN KEY (store_id) REFERENCES stores (id);


CREATE TABLE store_contacts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id   BIGINT                                  NOT NULL,
    type       VARCHAR(32)                             NOT NULL,
    value      VARCHAR(512)                            NOT NULL,
    comment    VARCHAR(512),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_store_contacts PRIMARY KEY (id)
);

ALTER TABLE store_contacts
    ADD CONSTRAINT fk_store_contacts_on_store FOREIGN KEY (store_id) REFERENCES stores (id);

CREATE INDEX idx_store_contacts_store_id ON store_contacts (store_id);
