-- Store-scoped catalog: manufacturers, categories, products, product images + global stock statuses.

CREATE TABLE manufacturers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_manufacturers PRIMARY KEY (id),
    CONSTRAINT uq_manufacturers_store_name UNIQUE (store_id, name)
);

ALTER TABLE manufacturers
    ADD CONSTRAINT fk_manufacturers_on_store FOREIGN KEY (store_id) REFERENCES stores (id);
CREATE INDEX idx_manufacturers_store_id ON manufacturers (store_id);


CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id    BIGINT       NOT NULL,
    parent_id   BIGINT,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_on_store FOREIGN KEY (store_id) REFERENCES stores (id);
ALTER TABLE categories
    ADD CONSTRAINT fk_categories_on_parent FOREIGN KEY (parent_id) REFERENCES categories (id);
CREATE INDEX idx_categories_store_id ON categories (store_id);
CREATE INDEX idx_categories_parent_id ON categories (parent_id);
CREATE UNIQUE INDEX uq_categories_root_name
    ON categories (store_id, name) WHERE parent_id IS NULL;
CREATE UNIQUE INDEX uq_categories_child_name
    ON categories (store_id, parent_id, name) WHERE parent_id IS NOT NULL;


CREATE TABLE stock_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(64)  NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_stock_statuses PRIMARY KEY (id),
    CONSTRAINT uq_stock_statuses_code UNIQUE (code)
);

INSERT INTO stock_statuses (code, name)
VALUES ('IN_STOCK', 'В наявності'),
       ('OUT_OF_STOCK', 'Немає в наявності'),
       ('PREORDER', 'Передзамовлення');


CREATE TABLE products
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id          BIGINT         NOT NULL,
    category_id       BIGINT,
    manufacturer_id   BIGINT,
    stock_status_id   BIGINT         NOT NULL,
    name              VARCHAR(255)   NOT NULL,
    sku               VARCHAR(128),
    code              VARCHAR(128)   NOT NULL,
    description       TEXT,
    partner_price     NUMERIC(19, 4) NOT NULL,
    recommended_price NUMERIC(19, 4) NOT NULL,
    quantity          INTEGER        NOT NULL DEFAULT 0,
    weight            NUMERIC(12, 3),
    width             NUMERIC(12, 3),
    height            NUMERIC(12, 3),
    length            NUMERIC(12, 3),
    status            VARCHAR(32)    NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products ADD CONSTRAINT fk_products_on_store
    FOREIGN KEY (store_id) REFERENCES stores (id);
ALTER TABLE products ADD CONSTRAINT fk_products_on_category
    FOREIGN KEY (category_id) REFERENCES categories (id);
ALTER TABLE products ADD CONSTRAINT fk_products_on_manufacturer
    FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (id);
ALTER TABLE products ADD CONSTRAINT fk_products_on_stock_status
    FOREIGN KEY (stock_status_id) REFERENCES stock_statuses (id);

ALTER TABLE products ADD CONSTRAINT uq_products_store_code UNIQUE (store_id, code);
CREATE UNIQUE INDEX uq_products_store_sku ON products (store_id, sku) WHERE sku IS NOT NULL;
CREATE INDEX idx_products_store_id ON products (store_id);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_manufacturer_id ON products (manufacturer_id);
CREATE INDEX idx_products_stock_status_id ON products (stock_status_id);
CREATE INDEX idx_products_created_at ON products (created_at);
CREATE INDEX idx_products_name_lower ON products (lower(name));


CREATE TABLE product_images
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id        BIGINT       NOT NULL,
    storage_key       VARCHAR(512) NOT NULL,
    content_type      VARCHAR(128),
    size_bytes        BIGINT,
    original_filename VARCHAR(255),
    sort_order        INTEGER      NOT NULL DEFAULT 0,
    is_primary        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

ALTER TABLE product_images ADD CONSTRAINT fk_product_images_on_product
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE;
CREATE INDEX idx_product_images_product_id ON product_images (product_id);
