CREATE TABLE manufacturers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id    BIGINT NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_manufacturers PRIMARY KEY (id),
    CONSTRAINT uq_manufacturers_store_name UNIQUE (store_id, name)
);

ALTER TABLE manufacturers
    ADD CONSTRAINT FK_MANUFACTURERS_ON_STORE FOREIGN KEY (store_id) REFERENCES stores (id);

CREATE INDEX idx_manufacturers_store_id ON manufacturers (store_id);
