-- Seller orders (store-scoped) + items + shipment + status lookup.

CREATE TABLE order_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(64)  NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_order_statuses PRIMARY KEY (id),
    CONSTRAINT uq_order_statuses_code UNIQUE (code)
);

INSERT INTO order_statuses (code, name)
VALUES ('NEW', 'Нове'),
       ('PROCESSING', 'В обробці'),
       ('SHIPPED', 'Відправлено'),
       ('DELIVERED', 'Доставлено'),
       ('CANCELLED', 'Скасовано');


CREATE TABLE orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id              BIGINT         NOT NULL,
    buyer_id              BIGINT         NOT NULL,
    status_id             BIGINT         NOT NULL,
    recipient_first_name  VARCHAR(255)   NOT NULL,
    recipient_last_name   VARCHAR(255)   NOT NULL,
    recipient_phone       VARCHAR(32),
    recipient_email       VARCHAR(255),
    delivery_method_code  VARCHAR(64)    NOT NULL,
    delivery_type         VARCHAR(32)    NOT NULL,
    delivery_country      VARCHAR(128),
    delivery_region       VARCHAR(128),
    delivery_city         VARCHAR(128),
    delivery_address      VARCHAR(512),
    delivery_extra        VARCHAR(512),
    delivery_warehouse_no VARCHAR(64),
    payment_method_code   VARCHAR(64)    NOT NULL,
    prepayment            NUMERIC(19, 4),
    currency              VARCHAR(3)     NOT NULL,
    subtotal              NUMERIC(19, 4) NOT NULL,
    discount_total        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    shipping_total        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total                 NUMERIC(19, 4) NOT NULL,
    comment               TEXT,
    internal_comment      TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders ADD CONSTRAINT fk_orders_on_store
    FOREIGN KEY (store_id) REFERENCES stores (id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_on_status
    FOREIGN KEY (status_id) REFERENCES order_statuses (id);

CREATE INDEX idx_orders_store_id ON orders (store_id);
CREATE INDEX idx_orders_buyer_id ON orders (buyer_id);
CREATE INDEX idx_orders_status_id ON orders (status_id);
CREATE INDEX idx_orders_created_at ON orders (created_at);
CREATE INDEX idx_orders_recipient_last_name_lower ON orders (lower(recipient_last_name));


CREATE TABLE order_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id      BIGINT         NOT NULL,
    product_id    BIGINT         NOT NULL,
    sku           VARCHAR(128),
    code          VARCHAR(128)   NOT NULL,
    name          VARCHAR(255)   NOT NULL,
    quantity      INTEGER        NOT NULL,
    partner_price NUMERIC(19, 4) NOT NULL,
    sale_price    NUMERIC(19, 4) NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_on_order
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
CREATE INDEX idx_order_items_order_id ON order_items (order_id);


CREATE TABLE order_shipments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id        BIGINT      NOT NULL,
    carrier_code    VARCHAR(64),
    tracking_number VARCHAR(128),
    delivery_status VARCHAR(64),
    raw_payload     JSONB       NOT NULL DEFAULT '{}',
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_shipments PRIMARY KEY (id),
    CONSTRAINT uq_order_shipments_order UNIQUE (order_id)
);

ALTER TABLE order_shipments ADD CONSTRAINT fk_order_shipments_on_order
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
