CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id    BIGINT NOT NULL,
    parent_id   BIGINT,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_on_store FOREIGN KEY (store_id) REFERENCES stores (id);
ALTER TABLE categories
    ADD CONSTRAINT fk_categories_on_parent FOREIGN KEY (parent_id) REFERENCES categories (id);

CREATE INDEX idx_categories_store_id ON categories (store_id);
CREATE INDEX idx_categories_parent_id ON categories (parent_id);

-- унікальність назви серед сіблінгів (root та non-root окремо, бо NULL-и в Postgres різні)
CREATE UNIQUE INDEX uq_categories_root_name
    ON categories (store_id, name) WHERE parent_id IS NULL;
CREATE UNIQUE INDEX uq_categories_child_name
    ON categories (store_id, parent_id, name) WHERE parent_id IS NOT NULL;
