CREATE TABLE stock_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(64)  NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_stock_statuses PRIMARY KEY (id),
    CONSTRAINT uq_stock_statuses_code UNIQUE (code)
);

INSERT INTO stock_statuses (code, name)
VALUES ('IN_STOCK', 'В наявності'),
       ('OUT_OF_STOCK', 'Немає в наявності'),
       ('PREORDER', 'Передзамовлення');
